apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/soukupj00/ada502-fireguard-project-frontend:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          envFrom:
            - secretRef:
                name: fireguard-secrets
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      restartPolicy: Always
      volumes:
        - name: nginx-config-volume
          configMap:
            name: frontend-nginx-config
